# Site settings
title: "WebScal3r"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: webscal3r@gmail.com
description: >
  Scalability คือ การที่ระบบสามารถปรับเปลี่ยนเพื่อรองรับจำนวนผู้ใช้งาน ข้อมูล และการใช้งานต่างๆ ที่เปลี่ยนแปลงไปได้อย่างมีประสิทธิภาพ คุ้มค่ากับสิ่งที่ลงทุน และไม่กระทบต่อประสบการณ์การใช้งาน
url: "http://webscal3r.github.io" # the base hostname & protocol for your site
github_username:  webscal3r

# Build settings
markdown: kramdown
